name: moru
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_locales: ^2.0.2
  flutter_svg: ^1.1.3
  google_fonts: ^3.0.1
  responsive_builder: ^0.4.2
  fluro: ^2.0.3
  flutter_animation_progress_bar: ^2.2.1
  dotted_border: ^2.0.0+2
  intl: ^0.17.0
  photo_view: 0.13.0
  card_swiper: 2.0.1
  flutter_xlider:
    git:
      url: https://github.com/Ali-Azmoud/flutter_xlider.git
      ref: master

  #For Mobile
  convex_bottom_bar: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/locales/
    - assets/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Moru
      fonts:
        - asset: fonts/Moru.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#   fonts:
#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
