import 'package:flutter/widgets.dart';
/// Flutter icons Moru
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Moru
///      fonts:
///       - asset: fonts/Moru.ttf
///
///
///
///
class Moru {
  Moru._();

  static const _kFontFam = 'Moru';
  static const String? _kFontPkg = null;

  static const IconData gallery = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gif = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loop = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_add = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_off = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rec_mic = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData record = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signup = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smile = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teeth = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teeth_add = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teeth_calen = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teeth_cross = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_arrow = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_arrow = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_arrow = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emoji = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
